### ISSUE TITLE
update dependencies for security vulnerabilities 

### ISSUE THREAD

**Issue by dhylbert** [parshap/http-route#1]
The following package versions have known security vulnerabilities:
* cookie-signature@1.0.1
* qs@0.6.5
* send@0.1.4

I'm pretty sure this can be fixed by upgrading `connect` to `v3`. I'll test and submit a PR if so.

**Comment by parshap** [comment]
Other than tests/examples, `connect` is actually only used for a small utility function: https://github.com/parshap/http-route/blob/7c66a89f71f493e75553211db238c5a5f320bcf6/lib/path.js#L24

It looks like this has been extracted to its [own module](https://www.npmjs.com/package/parseurl), so it should be pretty easy to drop `connect` as a dependency completely.
